name: Zendesk Continuous Integration

on:
  push:
    branches:
      - master
      - main
      - next
  pull_request:
    branches:
      - '**'

jobs:
  publish-docs:
    name: Publish documentation
    runs-on: [self-hosted, zendesk-stable]
    if: github.actor != 'github-actions[bot]' && github.event_name == 'push' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/main' || github.ref == 'refs/heads/next')
    steps:
      - uses: zendesk/checkout@v2
      - uses: zendesk/setup-node@v2
        with:
          node-version: 16
      - id: find-yarn-cache-folder
        name: Find Yarn's cache folder
        run: echo "::set-output name=path::$(yarn config get cacheFolder)"
      - name: Cache Yarn's cache folder
        uses: zendesk/cache@v2.1.6
        with:
          path: ${{ steps.find-yarn-cache-folder.outputs.path }}
          key: yarn-cache-folder-os-${{ runner.os }}-node-${{ env.node-version }}-${{ hashFiles('yarn.lock') }}
          restore-keys: |
            yarn-cache-folder-os-${{ runner.os }}-node-${{ env.node-version }}-
            yarn-cache-folder-os-${{ runner.os }}-
      - id: find-yarn-cache-folder-docs
        name: Find Docs Yarn's cache folder
        run: |
          cd docs
          echo "::set-output name=path::$(yarn config get cacheFolder)"
      - name: Cache Docs Yarn's cache folder
        uses: zendesk/cache@v2.1.6
        with:
          path: ${{ steps.find-yarn-cache-folder-docs.outputs.path }}
          key: yarn-cache-folder-docs-os-${{ runner.os }}-node-${{ env.node-version }}-${{ hashFiles('docs/yarn.lock') }}
          restore-keys: |
            yarn-cache-folder-docs-os-${{ runner.os }}-node-${{ env.node-version }}-
            yarn-cache-folder-docs-os-${{ runner.os }}-
      - name: Install dependencies
        run: |
          yarn install --immutable
          cd docs
          yarn install --immutable
      - name: Build and release docs
        run: |
          cd docs
          ./deploy.sh
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
